# Generated by Django 5.2 on 2025-04-30 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DeckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('label', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('label', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('num_positions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=700)),
                ('theme', models.CharField(max_length=55)),
                ('deck_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='decks', to='rootedapi.decktype')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('meaning', models.CharField(max_length=1500)),
                ('orientation_enabled', models.BooleanField(default=False)),
                ('image_path', models.ImageField(null=True, upload_to='cards')),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rootedapi.cardtype')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rootedapi.deck')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_element', to='rootedapi.element')),
            ],
        ),
        migrations.CreateModel(
            name='CardKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rootedapi.card')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rootedapi.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(related_name='keyword_cards', through='rootedapi.CardKeyword', to='rootedapi.keyword'),
        ),
        migrations.CreateModel(
            name='Sage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferred_deck', to='rootedapi.deck')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_seed', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(max_length=100)),
                ('entry_text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(blank=True, choices=[('calm', 'Calm'), ('hopeful', 'Hopeful'), ('reflective', 'Reflective'), ('joyful', 'Joyful'), ('grateful', 'Grateful'), ('peaceful', 'Peaceful'), ('curious', 'Curious'), ('empowered', 'Empowered'), ('grounded', 'Grounded'), ('anxious', 'Anxious'), ('melancholy', 'Melancholy'), ('frustrated', 'Frustrated'), ('overwhelmed', 'Overwhelmed'), ('lonely', 'Lonely'), ('grieving', 'Grieving'), ('vulnerable', 'Vulnerable'), ('lost', 'Lost'), ('inspired', 'Inspired'), ('motivated', 'Motivated'), ('determined', 'Determined'), ('rejuvenated', 'Rejuvenated')], max_length=25, null=True)),
                ('lunar_phase', models.CharField(blank=True, choices=[('New Moon', '🌑'), ('Waxing Moon', '🌔'), ('Full Moon', '🌕'), ('Waning Moon', '🌖')], max_length=25, null=True)),
                ('sage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='rootedapi.sage')),
                ('spread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_spread', to='rootedapi.spread')),
            ],
        ),
        migrations.CreateModel(
            name='SpreadPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
                ('prompt', models.CharField(max_length=150)),
                ('spread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='rootedapi.spread')),
            ],
        ),
        migrations.CreateModel(
            name='EntryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rootedapi.card')),
                ('journalEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_cards', to='rootedapi.journalentry')),
                ('spread_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rootedapi.spreadposition')),
            ],
        ),
    ]
